version: '3.8'


services:
  api:
    build: .
    ports:
      - "8082:80"
    depends_on:
      - db 
 
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pessoadb
    ports:
      - "5432:5432"