version: '3.8'


services:
  api:
    container_name: api-pessoa
    image: api-pessoa8:latest
    build: .
    ports:
      - "8082:80"
    depends_on:
      - db 
 
  db:
    container_name: banco-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pessoadb
    ports:
      - "5432:5432"
    volumes:
      - /C/Docker:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local